import * as stylex from "@stylexjs/stylex";

import { color, font, space } from "#design/tokens.stylex";
export const feedStyles = stylex.create({
  entryActions: { display: "flex", alignItems: "center", gap: space.sm },
  feed: {
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: color.line,
    paddingLeft: { default: space.lg, "@media (max-width: 767px)": space.sm },
    marginTop: space.lg,
  },
  thought: {
    paddingBlock: space.md,
    borderBottomWidth: { default: 1, ":last-child": 0 },
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  entryHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: space.sm,
    marginBottom: space.sm,
  },
  timestamp: { fontFamily: font.mono, fontSize: "12px", color: color.muted },
  body: {
    color: color.secondary,
    lineHeight: 1.8,
    overflowWrap: "anywhere",
    minWidth: 0,
  },
  timeline: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: space.xl,
    paddingBottom: space.xxl,
    marginTop: space.xl,
  },
  axis: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: { default: "50%", "@media (max-width: 767px)": "12px" },
    width: "2px",
    backgroundColor: color.line,
  },
  yearAnchor: {
    position: "relative",
    alignSelf: { default: "center", "@media (max-width: 767px)": "flex-start" },
    marginBottom: space.xs,
  },
  year: {
    borderRadius: "999px",
    paddingBlock: "4px",
    paddingInline: "18px",
    color: color.onAccent,
    backgroundColor: color.accent,
    fontSize: "20px",
    fontWeight: font.bold,
  },
  event: {
    position: "relative",
    width: {
      default: "calc(50% - 32px)",
      "@media (max-width: 767px)": "calc(100% - 40px)",
    },
    alignSelf: {
      default: "flex-start",
      "@media (max-width: 767px)": "flex-end",
    },
  },
  eventRight: { alignSelf: "flex-end" },
  dot: {
    position: "absolute",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    top: "50%",
    right: { default: "-43px", "@media (max-width: 767px)": "auto" },
    left: { default: "auto", "@media (max-width: 767px)": "-37px" },
    transform: "translateY(-50%)",
  },
  dotFill: {
    display: "block",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    backgroundColor: color.accent,
  },
  dotRight: {
    right: "auto",
    left: { default: "-41px", "@media (max-width: 767px)": "-37px" },
  },
  eventCard: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "14px",
    padding: "20px",
    backgroundColor: color.canvas,
  },
  eventTitle: {
    fontSize: "22px",
    fontWeight: font.bold,
    marginBlock: "12px",
    color: color.text,
  },
});
