import * as stylex from "@stylexjs/stylex";

import { color, font, shadow, space } from "#design/tokens.stylex";
export const styles = stylex.create({
  list: { display: "flex", flexDirection: "column", gap: "20px" },
  row: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: space.sm,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: space.md,
  },
  sorting: {
    display: "inline-flex",
    gap: "4px",
    padding: "4px",
    borderRadius: "9px",
    backgroundColor: color.surfaceMuted,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
  },
  sort: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    paddingBlock: "7px",
    paddingInline: "12px",
    color: color.muted,
    borderRadius: "6px",
    fontSize: "14px",
  },
  selected: {
    backgroundColor: color.surfaceSelected,
    color: color.text,
    boxShadow: shadow.subtle,
  },
  badges: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    marginLeft: "auto",
  },
  badge: {
    paddingBlock: "3px",
    paddingInline: "10px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "999px",
    fontSize: "12px",
    color: color.secondary,
    boxShadow: shadow.subtle,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(auto-fill, minmax(200px, 260px))",
      "@media (max-width: 600px)": "repeat(2, minmax(0, 1fr))",
    },
    gap: "20px",
    alignItems: "start",
  },
  card: { minWidth: 0 },
  previewFrame: { position: "relative" },
  preview: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    aspectRatio: "1",
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "9px",
    backgroundColor: color.surfaceMuted,
    color: color.muted,
  },
  thumbnail: { width: "100%", height: "100%", objectFit: "cover" },
  file: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: space.md,
    fontSize: font.control,
    textTransform: "uppercase",
  },
  details: {
    paddingBlock: "10px",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  name: {
    fontSize: "13px",
    fontWeight: font.medium,
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
    color: color.text,
  },
  metadata: { fontSize: "11px", color: color.muted },
  actions: {
    position: "absolute",
    bottom: "8px",
    right: "8px",
    display: "flex",
    gap: space.xs,
    alignItems: "center",
    padding: "4px",
    borderRadius: "8px",
    backgroundColor: color.surface,
    boxShadow: shadow.subtle,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    opacity: {
      default: 0,
      ":is([data-file-card]:hover *, [data-file-card]:focus-within *)": 1,
      "@media (hover: none), (pointer: coarse)": 1,
    },
    pointerEvents: {
      default: "none",
      ":is([data-file-card]:hover *, [data-file-card]:focus-within *)": "auto",
      "@media (hover: none), (pointer: coarse)": "auto",
    },
  },
  icon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "5px",
    borderRadius: "5px",
    backgroundColor: "transparent",
    color: { default: color.muted, ":hover": color.accentText },
    cursor: "pointer",
  },
  danger: { color: { default: color.muted, ":hover": color.dangerText } },
  muted: { color: color.muted, fontSize: "12px" },
  error: { color: color.dangerText },
  pagination: {
    display: "flex",
    justifyContent: "center",
    gap: space.md,
    fontSize: font.control,
    color: color.muted,
  },
});
