import * as stylex from "@stylexjs/stylex";

import {
  font,
  media,
  motionToken,
  shape,
  material,
} from "#design/tokens.stylex";

import { recordMarker } from "../../_design/object-feedback.stylex";
export const styles = stylex.create({
  root: {
    margin: 0,
    padding: 0,
    borderWidth: 0,
    minWidth: 0,
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    opacity: {
      default: 0,
      [media.deskPhone]: 1,
      [media.touch]: 1,
      [stylex.when.ancestor(":hover", recordMarker)]: 1,
      [stylex.when.ancestor(":has(:focus-visible)", recordMarker)]: 1,
    },
    transitionProperty: "opacity",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
  },
  pinned: { opacity: 1 },
  interactive: {
    pointerEvents: {
      default: "none",
      [media.deskPhone]: "auto",
      [media.touch]: "auto",
      [stylex.when.ancestor(":hover", recordMarker)]: "auto",
      [stylex.when.ancestor(":has(:focus-visible)", recordMarker)]: "auto",
    },
  },
  pinnedInteractive: { pointerEvents: "auto" },
  ring: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    overflow: "visible",
  },
  title: {
    fill: material.playerText,
    fontFamily: font.mono,
    fontSize: font.small,
    letterSpacing: "1.4px",
  },
  rail: {
    fill: "none",
    stroke: material.playerRail,
    strokeWidth: 2,
    strokeLinecap: "round",
    opacity: 0.6,
  },
  fill: {
    fill: "none",
    stroke: material.playerAccent,
    strokeWidth: 2.5,
    strokeLinecap: "round",
  },
  dot: { fill: material.playerText },
  seek: {
    fill: "none",
    stroke: { default: "transparent", ":focus-visible": material.playerHover },
    strokeWidth: 20,
    strokeLinecap: "round",
    outline: "none",
    cursor: "pointer",
    touchAction: "none",
  },
  button: {
    position: "absolute",
    display: "grid",
    placeItems: "center",
    width: shape.touch,
    height: shape.touch,
    padding: 0,
    borderWidth: 0,
    borderRadius: shape.round,
    backgroundColor: "transparent",
    color: {
      default: material.playerText,
      ":hover": material.playerText,
      ":focus-visible": material.playerText,
    },
    opacity: { default: 0.8, ":hover": 1, ":focus-visible": 1 },
    transitionProperty: "opacity",
    transitionDuration: motionToken.fast,
  },
  pinnedIcon: { transform: "rotate(35deg)" },
  pin: { left: "29.17%", top: "86.08%", transform: "translate(-50%, -50%)" },
  play: { left: "50%", top: "91.67%", transform: "translate(-50%, -50%)" },
  mode: { left: "70.83%", top: "86.08%", transform: "translate(-50%, -50%)" },
  previous: {
    left: "13.92%",
    top: "70.83%",
    transform: "translate(-50%, -50%)",
  },
  next: { left: "86.08%", top: "70.83%", transform: "translate(-50%, -50%)" },
  pinIcon: {
    width: "15px",
    height: "15px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.6,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
  },
  icon: { width: "13px", height: "13px", fill: "currentColor" },
  reverse: { transform: "rotate(180deg)" },
  time: {
    position: "absolute",
    top: "64%",
    left: 0,
    right: 0,
    fontFamily: font.mono,
    fontSize: font.tiny,
    color: material.playerText,
    fontVariantNumeric: "tabular-nums",
    letterSpacing: "0.5px",
  },
});
