import * as stylex from "@stylexjs/stylex";

import { color, font, media, shape, space } from "#design/tokens.stylex";

export const editorStyles = stylex.create({
  form: {
    width: "100%",
    maxWidth: "1000px",
    marginInline: "auto",
    display: "flex",
    flexDirection: "column",
    gap: space.xl,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: space.md,
    margin: 0,
    padding: { default: space.lg, [media.phone]: space.md },
    minWidth: 0,
    borderWidth: shape.fine,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.card,
    backgroundColor: color.surface,
  },
  heading: {
    margin: 0,
    color: color.text,
    fontSize: font.heading,
    fontWeight: font.medium,
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: space.xs,
  },
  link: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xxs,
    color: color.accentText,
    fontSize: font.small,
    textDecoration: "underline",
    textUnderlineOffset: "3px",
  },
  sectionTitle: {
    margin: 0,
    fontFamily: font.mono,
    fontSize: font.small,
    fontWeight: font.medium,
  },
  fieldsGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [media.phone]: "minmax(0, 1fr)",
    },
    rowGap: space.sm,
    columnGap: space.lg,
  },
  passages: {
    display: "grid",
    gridTemplateColumns: {
      default: "180px minmax(0, 1fr)",
      [media.phone]: "minmax(0, 1fr)",
    },
    gap: space.lg,
  },
  passageDirectory: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    minWidth: 0,
  },
  passageList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    maxHeight: "280px",
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  passageRow: {
    display: "flex",
    alignItems: "center",
    color: color.muted,
    borderBottomWidth: shape.fine,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
    backgroundColor: color.surface,
  },
  selectedPassage: { color: color.text, borderBottomColor: color.accent },
  passageButton: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    flex: "1",
    minWidth: 0,
    minHeight: "44px",
    paddingBlock: "10px",
    paddingInline: space.xxs,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  passageNumber: { fontFamily: font.mono, fontSize: "10px" },
  passageSummary: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: font.small,
  },
  group: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    minWidth: 0,
  },
  row: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: space.xs,
  },
  muted: {
    color: color.muted,
    fontSize: font.small,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
  },
  error: {
    color: color.dangerText,
    fontSize: font.small,
    margin: 0,
    overflowWrap: "anywhere",
  },
  recordSummary: {
    display: "flex",
    flexDirection: "column",
    gap: space.xxs,
    minWidth: 0,
    flex: "1",
  },
  empty: {
    margin: 0,
    paddingBlock: space.lg,
    textAlign: "center",
    color: color.muted,
    fontSize: font.bodySize,
  },
  importSection: {
    borderTopWidth: shape.fine,
    borderTopStyle: "solid",
    borderTopColor: color.line,
    marginTop: space.md,
  },
  importSummary: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    paddingBlock: space.md,
    cursor: "pointer",
    fontSize: font.small,
  },
  importBody: {
    display: "flex",
    flexDirection: "column",
    gap: space.lg,
    paddingBottom: space.xs,
  },
  importLink: { display: "flex", alignItems: "flex-end", gap: space.xs },
  libraryList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    maxHeight: "300px",
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  libraryRow: {
    display: "flex",
    alignItems: "center",
    gap: space.sm,
    paddingBlock: space.sm,
    borderBottomWidth: shape.fine,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  previewPlayer: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    minWidth: 0,
    paddingBlock: space.sm,
  },
  previewTime: {
    whiteSpace: "nowrap",
    fontFamily: font.mono,
    fontSize: "10px",
    color: color.muted,
  },
  seek: {
    minWidth: 0,
    flex: "1",
    height: "2px",
    accentColor: color.accent,
    cursor: "pointer",
  },
});
