import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  shape,
  space,
} from "#design/tokens.stylex";

export const listStyles = stylex.create({
  list: { display: "flex", flexDirection: "column", gap: space.xl },
  posts: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    minWidth: 0,
    borderTopWidth: shape.fine,
    borderTopStyle: "solid",
    borderTopColor: color.line,
  },
  post: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) 112px auto",
      [media.phone]: "minmax(0, 1fr) auto",
    },
    alignItems: "center",
    columnGap: { default: space.lg, [media.phone]: space.sm },
    minHeight: { default: "56px", [media.phone]: "88px" },
    padding: 0,
    backgroundColor: {
      default: "transparent",
      ":hover": { default: color.surfaceMuted, [media.touch]: "transparent" },
      ":focus-within": color.surfaceMuted,
    },
    transitionProperty: "background-color",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    borderBottomWidth: { default: shape.fine, ":last-child": 0 },
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  postControls: {
    display: "flex",
    alignItems: "center",
    gap: space.md,
    flexShrink: 0,
  },
  postTitle: {
    minWidth: 0,
    gridColumn: { default: "auto", [media.phone]: "1 / -1" },
    minHeight: shape.touch,
    padding: 0,
    fontSize: font.bodySize,
    fontWeight: font.regular,
    lineHeight: 1.5,
    color: { default: color.text, ":hover": color.accentText },
    transitionProperty: "color",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    textAlign: "left",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  postDate: {
    minWidth: 0,
    flexShrink: 0,
    fontSize: font.small,
    color: color.muted,
    whiteSpace: "nowrap",
  },
  postVisibility: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    width: "88px",
    flexShrink: 0,
    minHeight: "30px",
    padding: 0,
    fontSize: font.control,
    color: { default: color.muted, ":hover": color.accentText },
    backgroundColor: "transparent",
    transitionProperty: "color",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  meta: { fontSize: "14px", color: color.muted, whiteSpace: "nowrap" },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "12px",
    flexShrink: 0,
  },
  iconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    padding: 0,
    color: { default: color.muted, ":hover": color.accentText },
    borderRadius: "6px",
    backgroundColor: "transparent",
    transitionProperty: "color",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  deleteButton: { color: { default: color.muted, ":hover": color.dangerText } },
  pagination: {
    display: "flex",
    gap: space.md,
    alignItems: "center",
    justifyContent: "center",
    color: color.muted,
    fontSize: "13px",
    paddingBlock: space.md,
  },
});
