import * as stylex from "@stylexjs/stylex";

import { color, font, shadow, space } from "#design/tokens.stylex";

export const listStyles = stylex.create({
  list: { display: "flex", flexDirection: "column", gap: space.xl },
  tableWrap: {
    overflowX: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "14px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "680px",
    textAlign: "center",
  },
  th: {
    paddingBlock: "14px",
    paddingInline: "20px",
    backgroundColor: color.surfaceMuted,
    color: color.muted,
    fontSize: "12px",
    fontWeight: font.medium,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  td: {
    padding: "20px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
    verticalAlign: "middle",
  },
  lastCell: { borderBottomWidth: 0 },
  postTitle: {
    fontSize: "16px",
    fontWeight: font.semibold,
    color: { default: color.text, ":hover": color.accentText },
    textAlign: "center",
    cursor: "pointer",
  },
  meta: { fontSize: "14px", color: color.muted, whiteSpace: "nowrap" },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "12px",
    flexShrink: 0,
  },
  iconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    padding: 0,
    color: { default: color.muted, ":hover": color.accentText },
    borderRadius: "6px",
    backgroundColor: "transparent",
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  deleteButton: { color: { default: color.muted, ":hover": color.dangerText } },
  segmented: {
    borderWidth: 0,
    margin: 0,
    display: "inline-flex",
    padding: "2px",
    backgroundColor: color.surfaceMuted,
    borderRadius: "9px",
    gap: "2px",
  },
  segment: {
    paddingBlock: "2px",
    paddingInline: "9px",
    lineHeight: "20px",
    fontSize: "12px",
    color: color.muted,
    borderRadius: "7px",
    cursor: "pointer",
    backgroundColor: "transparent",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  selected: {
    color: color.text,
    backgroundColor: color.surfaceSelected,
    boxShadow: shadow.subtle,
  },
  feed: {
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: color.line,
    paddingLeft: { default: space.lg, "@media (max-width: 767px)": space.sm },
    marginTop: space.lg,
  },
  thought: {
    paddingBlockStart: "12px",
    paddingBlockEnd: "40px",
    marginBottom: "40px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  entryHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: space.sm,
    marginBottom: space.sm,
  },
  timestamp: { fontFamily: font.mono, fontSize: "12px", color: color.muted },
  body: {
    color: color.secondary,
    lineHeight: 1.8,
    overflowWrap: "anywhere",
    minWidth: 0,
  },
  timeline: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    gap: space.xl,
    paddingBottom: space.xxl,
    marginTop: space.xl,
  },
  axis: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: { default: "50%", "@media (max-width: 767px)": "12px" },
    width: "2px",
    backgroundColor: color.line,
  },
  yearAnchor: {
    position: "relative",
    alignSelf: { default: "center", "@media (max-width: 767px)": "flex-start" },
    marginBottom: space.xs,
  },
  year: {
    borderRadius: "999px",
    paddingBlock: "4px",
    paddingInline: "18px",
    color: color.onAccent,
    backgroundColor: color.accent,
    fontSize: "20px",
    fontWeight: font.bold,
  },
  event: {
    position: "relative",
    width: {
      default: "calc(50% - 32px)",
      "@media (max-width: 767px)": "calc(100% - 40px)",
    },
    alignSelf: {
      default: "flex-start",
      "@media (max-width: 767px)": "flex-end",
    },
  },
  eventRight: { alignSelf: "flex-end" },
  dot: {
    position: "absolute",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    top: "50%",
    right: { default: "-43px", "@media (max-width: 767px)": "auto" },
    left: { default: "auto", "@media (max-width: 767px)": "-37px" },
    transform: "translateY(-50%)",
  },
  dotFill: {
    display: "block",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    backgroundColor: color.accent,
  },
  dotRight: {
    right: "auto",
    left: { default: "-41px", "@media (max-width: 767px)": "-37px" },
  },
  eventCard: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "14px",
    padding: "20px",
    backgroundColor: color.canvas,
  },
  eventTitle: {
    fontSize: "22px",
    fontWeight: font.bold,
    marginBlock: "12px",
    color: color.text,
  },
  pagination: {
    display: "flex",
    gap: space.md,
    alignItems: "center",
    justifyContent: "center",
    color: color.muted,
    fontSize: "13px",
    paddingBlock: space.md,
  },
});
