import * as stylex from "@stylexjs/stylex";

import { color, font, shadow, space } from "#design/tokens.stylex";

export const listStyles = stylex.create({
  list: { display: "flex", flexDirection: "column", gap: space.xl },
  tableWrap: {
    overflowX: "auto",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: "14px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    minWidth: "680px",
    textAlign: "center",
  },
  cellContent: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  th: {
    textAlign: "center",
    paddingBlock: "14px",
    paddingInline: "20px",
    backgroundColor: color.surfaceMuted,
    color: color.muted,
    fontSize: "12px",
    fontWeight: font.medium,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  td: {
    textAlign: "center",
    padding: "20px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
    verticalAlign: "middle",
  },
  lastCell: { borderBottomWidth: 0 },
  postTitle: {
    fontSize: "16px",
    fontWeight: font.semibold,
    color: { default: color.text, ":hover": color.accentText },
    textAlign: "center",
    cursor: "pointer",
  },
  meta: { fontSize: "14px", color: color.muted, whiteSpace: "nowrap" },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: "12px",
    flexShrink: 0,
  },
  iconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "30px",
    height: "30px",
    padding: 0,
    color: { default: color.muted, ":hover": color.accentText },
    borderRadius: "6px",
    backgroundColor: "transparent",
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  deleteButton: { color: { default: color.muted, ":hover": color.dangerText } },
  segmented: {
    borderWidth: 0,
    margin: 0,
    display: "inline-flex",
    padding: "2px",
    backgroundColor: color.surfaceMuted,
    borderRadius: "9px",
    gap: "2px",
  },
  segment: {
    paddingBlock: "2px",
    paddingInline: "9px",
    lineHeight: "20px",
    fontSize: "12px",
    color: color.muted,
    borderRadius: "7px",
    cursor: "pointer",
    backgroundColor: "transparent",
    opacity: { default: 1, ":disabled": 0.5 },
  },
  selected: {
    color: color.text,
    backgroundColor: color.surfaceSelected,
    boxShadow: shadow.subtle,
  },
  pagination: {
    display: "flex",
    gap: space.md,
    alignItems: "center",
    justifyContent: "center",
    color: color.muted,
    fontSize: "13px",
    paddingBlock: space.md,
  },
});
