import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  shadow,
  material,
} from "#design/tokens.stylex";

import { objectMarker } from "../../_design/object-feedback.stylex";

export const styles = stylex.create({
  bookFrame: { left: "-40px", top: "-12px", right: "24px", bottom: "-12px" },
  books: {
    width: "214px",
    position: "relative",
    paddingTop: "12px",
    paddingRight: "12px",
    paddingBottom: "28px",
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
  },
  bookBack: {
    position: "absolute",
    left: "-15px",
    top: "24px",
    width: "175px",
    height: "217px",
    borderTopLeftRadius: "3px",
    borderTopRightRadius: "6px",
    borderBottomRightRadius: "6px",
    borderBottomLeftRadius: "3px",
    backgroundColor: material.bookBack,
    transform: "rotate(-12deg)",
    boxShadow: shadow.contact,
    borderLeftWidth: "8px",
    borderLeftStyle: "solid",
    borderLeftColor: material.bookSpine,
  },
  book: {
    position: "relative",
    width: "175px",
    height: "224px",
    backgroundColor: material.book,
    backgroundImage: material.cloth,
    color: material.bookInk,
    boxShadow: `${shadow.book}, ${shadow.lifted}`,
    borderTopLeftRadius: "3px",
    borderTopRightRadius: "6px",
    borderBottomRightRadius: "6px",
    borderBottomLeftRadius: "3px",
    paddingTop: "24px",
    paddingRight: "24px",
    paddingBottom: "20px",
    paddingLeft: "28px",
    transform: {
      default: "rotate(-3deg)",
      [stylex.when.ancestor(":hover", objectMarker)]:
        "translate(7px, -2px) rotate(1deg)",
      [stylex.when.ancestor(":focus-visible", objectMarker)]:
        "translate(7px, -2px) rotate(1deg)",
      [media.reduce]: "rotate(-3deg)",
    },
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    borderBottomWidth: "6px",
    borderBottomStyle: "double",
    borderBottomColor: `${material.paperEdge}`,
  },
  bookIssue: {
    fontFamily: font.mono,
    fontSize: "7px",
    letterSpacing: "0.13em",
    lineHeight: 1.6,
  },
  bookTitle: {
    whiteSpace: "pre-line",
    fontFamily: font.display,
    fontSize: "32px",
    fontWeight: font.regular,
    lineHeight: 1.05,
    letterSpacing: "-0.03em",
  },
  bookAuthor: {
    fontFamily: font.mono,
    fontSize: "7px",
    letterSpacing: "0.13em",
  },
  bookmark: {
    position: "absolute",
    width: "15px",
    height: "32px",
    backgroundColor: color.accent,
    right: "19px",
    bottom: "-30px",
    clipPath: "polygon(0 0,100% 0,100% 100%,50% 75%,0 100%)",
  },
});
