import * as stylex from "@stylexjs/stylex";

import { shadow, shape, material } from "#design/tokens.stylex";

export const styles = stylex.create({
  coffee: {
    position: "relative",
    width: "100%",
    aspectRatio: "145 / 130",
    containerType: "inline-size",
  },
  saucer: {
    position: "absolute",
    width: "89.6552%",
    aspectRatio: "1",
    borderRadius: shape.round,
    backgroundImage: material.saucer,
    boxShadow: shadow.lifted,
  },
  handle: {
    position: "absolute",
    right: "2.7586%",
    top: "36.9231%",
    width: "22.069%",
    aspectRatio: "32 / 25",
    borderWidth: "5.5173cqw",
    borderStyle: "solid",
    borderColor: material.handle,
    borderTopLeftRadius: "calc(500cqw / 145)",
    borderTopRightRadius: "calc(1100cqw / 145)",
    borderBottomRightRadius: "calc(1100cqw / 145)",
    borderBottomLeftRadius: "calc(500cqw / 145)",
    boxShadow: shadow.detail,
  },
  cup: {
    position: "absolute",
    width: "62.7586%",
    aspectRatio: "1",
    left: "13.1034%",
    top: "13.8462%",
    borderRadius: shape.round,
    borderWidth: "4.8276cqw",
    borderStyle: "solid",
    borderColor: material.cup,
    backgroundImage: material.coffee,
    boxShadow: shadow.cup,
  },
  coffeeShine: {
    position: "absolute",
    left: "18.1818%",
    top: "15.5844%",
    width: "62.3377%",
    aspectRatio: "8 / 5",
    borderTopWidth: "1.3794cqw",
    borderTopStyle: "solid",
    borderTopColor: material.coffeeShine,
    borderRadius: shape.round,
    transform: "rotate(-25deg)",
  },
});
