import * as stylex from "@stylexjs/stylex";

import { color, font, shape, media, motionToken } from "#design/tokens.stylex";
export const itemStyles = stylex.create({
  appearance: (base: string, hover: string) => ({
    transform: {
      default: base,
      ":hover": hover,
      ":has(:focus-visible)": hover,
      [media.reduce]: base,
    },
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
  }),
  root: {
    position: "absolute",
    zIndex: { default: 2, ":hover": 5, ":focus-within": 5 },
    isolation: "isolate",
  },
  active: { zIndex: 10, userSelect: "none" },
  content: { position: "relative", transformOrigin: "top left" },
  editorTitle: {
    position: "absolute",
    top: "-14px",
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    maxWidth: "calc(100% + 32px)",
    borderRadius: shape.pill,
    backgroundColor: color.objectLabelBackground,
    color: color.objectLabel,
    fontFamily: font.mono,
    fontSize: "11px",
    zIndex: 3,
  },
  titleText: {
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    font: "inherit",
    paddingBlock: "5px",
    paddingInline: "8px",
    minHeight: "28px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    touchAction: "none",
    userSelect: "none",
  },
  editButton: {
    display: "grid",
    placeItems: "center",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    padding: "6px",
    minWidth: "30px",
    minHeight: "30px",
    borderRadius: shape.pill,
    cursor: "pointer",

    opacity: { default: 1, ":disabled": 0.5 },
  },
  resize: {
    position: "absolute",
    width: "22px",
    height: "22px",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: color.accent,
    borderRadius: "50%",
    backgroundColor: color.surface,
    touchAction: "none",
    zIndex: 2,
  },
  landing: {
    position: "absolute",
    left: 0,
    top: 0,
    pointerEvents: "none",
    borderWidth: "2px",
    borderStyle: "dashed",
    borderColor: color.accent,
    borderRadius: shape.control,
    backgroundColor: color.accentSurface,
    opacity: 0.5,
    zIndex: 1,
  },
  editorFrame: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.panel,
  },
  selectedFrame: { borderColor: color.accent },
});
