import * as stylex from "@stylexjs/stylex";

import { media, motionToken } from "#design/tokens.stylex";

export const itemStyles = stylex.create({
  root: {
    position: { default: "absolute", [media.deskCompact]: "relative" },
    minWidth: 0,
    maxWidth: "100%",
    justifySelf: "center",
    alignSelf: "center",
    zIndex: { default: 1, ":hover": 2, ":focus-within": 2 },
  },
  intro: {
    gridColumnStart: "1",
    gridColumnEnd: "-1",
    gridRowStart: "2",
    gridRowEnd: "3",
    left: { default: "50%", [media.deskCompact]: "auto" },
    top: {
      default: "49%",
      [media.deskShort]: "54%",
      [media.deskCompact]: "auto",
    },
    width: { default: "min(390px, 32cqw)", [media.deskCompact]: "100%" },
    maxWidth: "560px",
    transform: {
      default: "translate(-50%, -50%)",
      [media.deskCompact]: "none",
    },
  },
  lamp: {
    gridColumnStart: "1",
    gridColumnEnd: "-1",
    gridRowStart: "1",
    gridRowEnd: "2",
    width: "120px",
    height: "120px",
    left: { default: "50%", [media.deskCompact]: "auto" },
    top: {
      default: 0,
      [media.deskShort]: "-56px",
      [media.deskCompact]: "auto",
    },
    transform: { default: "translateX(-50%)", [media.deskCompact]: "none" },
    alignSelf: "start",
  },
  books: {
    gridColumnStart: "2",
    gridColumnEnd: { default: "5", [media.deskPhone]: "10" },
    gridRowStart: "3",
    gridRowEnd: "4",
    width: "214px",
    left: { default: "13%", [media.deskCompact]: "auto" },
    top: {
      default: "7%",
      [media.deskShort]: "1%",
      [media.deskCompact]: "auto",
    },
    marginTop: {
      default: 0,
      [media.deskTablet]: "-16px",
      [media.deskPhone]: "8px",
    },
    marginBottom: 0,
    justifySelf: "start",
    alignSelf: "start",
    transform: {
      default: "rotate(-9deg)",
      [media.deskCompact]: "rotate(-8deg)",
    },
  },
  display: {
    containerType: "inline-size",
    containerName: "desk-display",
    gridColumnStart: "1",
    gridColumnEnd: { default: "7", [media.deskPhone]: "-1" },
    gridRowStart: { default: "4", [media.deskPhone]: "6" },
    gridRowEnd: { default: "5", [media.deskPhone]: "7" },
    left: { default: "5%", [media.deskCompact]: "auto" },
    bottom: {
      default: "12%",
      [media.deskShort]: "5%",
      [media.deskCompact]: "auto",
    },
    width: {
      default: "clamp(360px, 27cqw, 390px)",
      [media.deskCompact]: "100%",
    },
    maxWidth: "420px",
    alignSelf: "start",
    transform: {
      default: "rotate(-7deg)",
      ":hover": {
        default: "translateY(-4px) rotate(0deg)",
        [media.deskTablet]: "translateY(-4px) rotate(0deg)",
        [media.deskPhone]: "translateY(-4px) rotate(0deg)",
      },
      // oxlint-disable-next-line @stylexjs/valid-styles -- Native :has() keeps keyboard feedback without retaining pointer-click focus.
      ":has(:focus-visible)": {
        default: "translateY(-4px) rotate(0deg)",
        [media.deskTablet]: "translateY(-4px) rotate(0deg)",
        [media.deskPhone]: "translateY(-4px) rotate(0deg)",
      },
      [media.deskTablet]: "rotate(-5deg)",
      [media.deskPhone]: "rotate(-3deg)",
    },
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
  },
  record: {
    gridColumnStart: { default: "8", [media.deskPhone]: "2" },
    gridColumnEnd: "-1",
    gridRowStart: { default: "3", [media.deskPhone]: "7" },
    gridRowEnd: { default: "4", [media.deskPhone]: "8" },
    right: {
      default: "8%",
      [media.deskShort]: "5%",
      [media.deskCompact]: "auto",
    },
    top: {
      default: "8%",
      [media.deskShort]: "2%",
      [media.deskCompact]: "auto",
    },
    width: {
      default: "clamp(250px, 34dvh, 290px)",
      [media.deskCompact]: "100%",
    },
    maxWidth: "320px",
    marginTop: {
      default: 0,
      [media.deskTablet]: "80px",
      [media.deskPhone]: "32px",
    },
    marginBottom: { default: 0, [media.deskPhone]: "24px" },
    alignSelf: "start",
    justifySelf: "end",
    transform: { default: "rotate(8deg)", [media.deskPhone]: "rotate(-6deg)" },
  },
  letter: {
    gridColumnStart: { default: "8", [media.deskPhone]: "3" },
    gridColumnEnd: { default: "12", [media.deskPhone]: "-1" },
    gridRowStart: "4",
    gridRowEnd: "5",
    right: {
      default: "9%",
      [media.deskShort]: "5%",
      [media.deskCompact]: "auto",
    },
    bottom: {
      default: "20%",
      [media.deskShort]: "5%",
      [media.deskCompact]: "auto",
    },
    width: { default: "225px", [media.deskCompact]: "260px" },
    maxWidth: {
      default: "calc(100% - 24px)",
      [media.deskPhone]: "calc(100% - 8px)",
    },
    marginTop: { default: 0, [media.deskTablet]: "80px" },
    marginBottom: 0,
    justifySelf: "end",
    transform: {
      default: "rotate(7deg)",
      [media.deskTablet]: "rotate(4deg)",
      [media.deskPhone]: "rotate(-4deg)",
    },
  },
  coffee: {
    gridColumnStart: { default: "5", [media.deskPhone]: "1" },
    gridColumnEnd: { default: "8", [media.deskPhone]: "6" },
    gridRowStart: "5",
    gridRowEnd: "6",
    width: { default: "145px", [media.deskPhone]: "116px" },
    height: { default: "130px", [media.deskPhone]: "104px" },
    marginTop: {
      default: 0,
      [media.deskTablet]: "-36px",
      [media.deskPhone]: "-56px",
    },
    marginBottom: 0,
    alignSelf: "end",
    justifySelf: "start",
    zIndex: 0,
    pointerEvents: "none",
    left: {
      default: "63%",
      [media.deskShort]: "67%",
      [media.deskCompact]: "auto",
    },
    bottom: {
      default: "5%",
      [media.deskShort]: "8%",
      [media.deskCompact]: "auto",
    },
    transform: "rotate(-23deg)",
  },
  pencil: {
    gridColumnStart: { default: "5", [media.deskPhone]: "9" },
    gridColumnEnd: { default: "7", [media.deskPhone]: "12" },
    gridRowStart: "3",
    gridRowEnd: "4",
    width: "118px",
    height: "35px",
    left: {
      default: "35%",
      [media.deskShort]: "33%",
      [media.deskCompact]: "auto",
    },
    top: { default: "22%", [media.deskCompact]: "auto" },
    transform: {
      default: "rotate(-21deg)",
      [media.deskTablet]: "rotate(16deg)",
      [media.deskPhone]: "rotate(68deg)",
    },
    marginTop: {
      default: 0,
      [media.deskTablet]: "80px",
      [media.deskPhone]: "105px",
    },
    alignSelf: {
      default: "end",
      [media.deskTablet]: "center",
      [media.deskPhone]: "start",
    },
    justifySelf: { default: "end", [media.deskCompact]: "center" },
    pointerEvents: "none",
  },
});
