import * as stylex from "@stylexjs/stylex";

import { color, font, shape, media } from "#design/tokens.stylex";
export const itemStyles = stylex.create({
  root: {
    position: "absolute",
    zIndex: { default: 2, ":hover": 5, ":focus-within": 5 },
    isolation: "isolate",
  },
  active: { zIndex: 10, userSelect: "none" },
  content: { position: "relative", transformOrigin: "top left" },
  handle: {
    position: "absolute",
    top: "-12px",
    left: "50%",
    transform: "translateX(-50%)",
    paddingBlock: "3px",
    paddingInline: "8px",
    minHeight: "24px",
    borderWidth: 0,
    borderRadius: shape.pill,
    backgroundColor: color.objectLabelBackground,
    color: color.objectLabel,
    fontFamily: font.mono,
    fontSize: "11px",
    touchAction: "none",
    userSelect: "none",
    opacity: { default: 0, [media.touch]: 1, ":focus-visible": 1 },
  },
  handleVisible: { opacity: 1 },
  resize: {
    position: "absolute",
    width: "22px",
    height: "22px",
    borderWidth: "2px",
    borderStyle: "solid",
    borderColor: color.accent,
    borderRadius: "50%",
    backgroundColor: color.surface,
    touchAction: "none",
    zIndex: 2,
  },
  landing: {
    position: "absolute",
    left: 0,
    top: 0,
    pointerEvents: "none",
    borderWidth: "2px",
    borderStyle: "dashed",
    borderColor: color.accent,
    borderRadius: shape.control,
    backgroundColor: color.accentSurface,
    opacity: 0.5,
    zIndex: 1,
  },
  editorFrame: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.panel,
  },
  selectedFrame: { borderColor: color.accent },
});
