import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  space,
  shadow,
  media,
  motionToken,
} from "#design/tokens.stylex";
export const editorStyles = stylex.create({
  dialog: {
    padding: 0,
    margin: "auto",
    width: "min(1120px, calc(100vw - 24px))",
    maxWidth: "1120px",
    maxHeight: "calc(100dvh - 32px)",
    overflow: "hidden",
    backgroundColor: color.surface,
    color: color.text,
    borderRadius: "3px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    boxShadow: `${shadow.lifted}, ${shadow.contact}`,
    fontFamily: font.body,
    "::backdrop": { backgroundColor: color.overlay },
  },
  form: {
    display: "flex",
    flexDirection: "column",
    maxHeight: "calc(100dvh - 34px)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: space.sm,
    paddingTop: "12px",
    paddingBottom: "12px",
    paddingInline: "clamp(16px,3vw,24px)",
  },
  body: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 1.25fr) minmax(0, 1fr)",
      [media.compact]: "minmax(0, 1fr)",
    },
    alignItems: "start",
    gap: "24px",
    overflowY: "auto",
    overscrollBehavior: "contain",
    paddingBlockStart: "12px",
    paddingBlockEnd: "16px",
    paddingInline: "clamp(16px,3vw,24px)",
    minHeight: 0,
  },
  formFields: { minWidth: 0 },
  preview: {
    position: { default: "sticky", [media.compact]: "relative" },
    top: 0,
    minWidth: 0,
    borderInlineStartWidth: { default: "1px", [media.compact]: 0 },
    borderInlineStartStyle: "solid",
    borderInlineStartColor: color.line,
    borderTopWidth: { default: 0, [media.compact]: "1px" },
    borderTopStyle: "solid",
    borderTopColor: color.line,
    paddingInlineStart: { default: "16px", [media.compact]: 0 },
    paddingTop: "8px",
  },
  previewLabel: {
    margin: 0,
    fontFamily: font.mono,
    fontSize: font.small,
    color: color.muted,
  },
  previewStage: {
    display: "grid",
    placeItems: "center",
    height: { default: "min(480px, 60dvh)", [media.compact]: "320px" },
    overflow: "hidden",
  },
  previewCanvas: {
    position: "relative",
    width: "1440px",
    containerType: "inline-size",
    containerName: "desk",
    transformOrigin: "top left",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: space.sm,
    paddingBlockStart: "12px",
    paddingBlockEnd: "12px",
    paddingInline: "clamp(16px,3vw,24px)",
  },
  tabs: {
    display: "flex",
    gap: "8px",
  },
  tab: {
    position: "relative",
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    width: "40px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: {
      default: color.text,
      ":hover": color.accent,
      ":focus-visible": color.accent,
    },
  },
  tabDot: {
    position: "absolute",
    bottom: "-10px",
    left: "calc(50% - 2.5px)",
    width: "5px",
    height: "5px",
    borderRadius: "50%",
    backgroundColor: "currentColor",
    opacity: { default: 0, ":is(button:hover *, button:focus-visible *)": 1 },
    transitionProperty: "opacity",
    transitionDuration: motionToken.normal,
  },
  activeDot: { opacity: 1 },
  srOnly: {
    position: "absolute",
    width: "1px",
    height: "1px",
    padding: 0,
    margin: "-1px",
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  restore: { marginInlineEnd: "auto", paddingInlineStart: 0 },
  statesGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: { default: "20px", [media.phone]: "12px" },
  },
  toggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBlock: "8px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
    fontSize: font.small,
  },
  movement: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    paddingBlock: "8px",
    paddingInlineStart: "12px",
    paddingInlineEnd: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: color.text,
    font: "inherit",
    cursor: "pointer",
  },
  switchTrack: {
    display: "inline-flex",
    alignItems: "center",
    width: "36px",
    height: "22px",
    padding: "3px",
    borderRadius: "20px",
    backgroundColor: color.surfaceStrong,
    transitionProperty: "background-color",
    transitionDuration: motionToken.fast,
  },
  switchOn: { backgroundColor: color.accent },
  switchThumb: {
    width: "16px",
    height: "16px",
    borderRadius: "50%",
    backgroundColor: color.inverse,
    transform: "translateX(0)",
    transitionProperty: "transform",
    transitionDuration: { default: motionToken.fast, [media.reduce]: "0s" },
  },
  thumbOn: { transform: "translateX(14px)" },
  selectedTab: { color: color.accent },
  sectionTitle: {
    margin: 0,
    fontFamily: font.mono,
    fontSize: font.small,
    fontWeight: font.medium,
  },
  fieldsGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      [media.phone]: "minmax(0, 1fr)",
    },
    rowGap: "12px",
    columnGap: "24px",
  },
  passages: {
    display: "grid",
    gridTemplateColumns: {
      default: "180px minmax(0, 1fr)",
      [media.phone]: "minmax(0, 1fr)",
    },
    gap: "24px",
  },
  passageDirectory: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    minWidth: 0,
  },
  passageList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    maxHeight: "280px",
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  passageRow: {
    display: "flex",
    alignItems: "center",
    color: color.muted,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
    backgroundColor: color.surface,
  },
  selectedPassage: { color: color.text, borderBottomColor: color.accent },
  dragHandle: {
    display: "grid",
    placeItems: "center",
    width: "24px",
    height: "40px",
    padding: 0,
    borderWidth: 0,
    color: "inherit",
    backgroundColor: "transparent",
    cursor: "grab",
    touchAction: "none",
  },
  passageButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flex: "1",
    minWidth: 0,
    paddingBlock: "10px",
    paddingInline: "4px",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "inherit",
    textAlign: "left",
    cursor: "pointer",
  },
  passageNumber: { fontFamily: font.mono, fontSize: "10px" },
  passageSummary: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: font.small,
  },
  fieldset: {
    display: "contents",
    borderWidth: 0,
    padding: 0,
    margin: 0,
    minWidth: 0,
  },
  group: {
    display: "flex",
    flexDirection: "column",
    gap: space.sm,
    minWidth: 0,
  },
  row: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: space.xs,
  },
  muted: {
    color: color.muted,
    fontSize: font.small,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
  },
  error: {
    color: color.dangerText,
    fontSize: font.small,
    margin: 0,
    overflowWrap: "anywhere",
  },
  recordSummary: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: 0,
    flex: "1",
  },
  empty: {
    margin: 0,
    paddingBlock: "48px",
    textAlign: "center",
    color: color.muted,
    fontFamily: font.display,
    fontSize: "22px",
  },
  importSection: {
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: color.line,
    marginTop: "16px",
  },
  importSummary: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    paddingBlock: "16px",
    cursor: "pointer",
    fontSize: font.small,
  },
  importBody: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
    paddingBottom: "8px",
  },
  importLink: { display: "flex", alignItems: "flex-end", gap: "8px" },
  libraryList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    maxHeight: "300px",
    overflowY: "auto",
    overscrollBehavior: "contain",
  },
  libraryRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    paddingBlock: "12px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: color.line,
  },
  previewPlayer: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    minWidth: 0,
    paddingBlock: "12px",
  },
  previewTime: {
    whiteSpace: "nowrap",
    fontFamily: font.mono,
    fontSize: "10px",
    color: color.muted,
  },
  seek: {
    minWidth: 0,
    flex: "1",
    height: "2px",
    accentColor: color.accent,
    cursor: "pointer",
  },
});
