import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  space,
  lighting,
  lampIntensity,
  material,
  shape,
} from "#design/tokens.stylex";

const wave = stylex.keyframes({
  "0%, 35%, 100%": { transform: "rotate(0deg)" },
  "7%, 21%": { transform: "rotate(18deg)" },
  "14%, 28%": { transform: "rotate(-10deg)" },
});
export const desk = stylex.create({
  viewport: { position: "relative", overflowX: "clip" },
  fixedViewport: { overflow: "clip", overflowClipMargin: shape.header },
  scaledCanvas: { position: "relative" },
  scene: {
    position: "relative",
    width: "100%",
    maxWidth: "1600px",
    marginInline: "auto",
  },
  frame: {
    position: "relative",
    containerType: "inline-size",
    containerName: "desk",
    transformOrigin: "top left",
  },
  canvas: { position: "relative", width: "100%" },
  glow: {
    position: "absolute",
    width: { default: "1150px", [media.deskCompact]: "140%" },
    height: "min(820px, 100%)",
    top: "0px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundImage: `radial-gradient(ellipse, ${material.glow} 0%, ${lighting.warmth} 40%, transparent 70%)`,
    opacity: lampIntensity.glowOpacity,
    transitionProperty: "opacity",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
    transitionTimingFunction: "ease",
    pointerEvents: "none",
  },
  intro: { width: "100%", textAlign: "center" },
  eyebrow: {
    fontFamily: font.mono,
    fontSize: font.large,
    letterSpacing: "0.05em",
    color: color.muted,
    marginBottom: space.md,
  },
  wave: {
    display: "inline-block",
    fontSize: "28px",
    marginRight: space.xs,
    transformOrigin: "70% 75%",
    animationName: { default: wave, [media.reduce]: "none" },
    animationDuration: motionToken.wave,
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  title: {
    fontFamily: font.handwritten,
    fontSize: {
      default: "clamp(60px, 6cqw, 90px)",
      [media.deskTablet]: "80px",
      [media.deskPhone]: "clamp(46px, 13cqw, 72px)",
    },
    letterSpacing: "-0.035em",
    fontWeight: font.regular,
    lineHeight: 1.25,
    outline: "none",
  },
  name: {
    display: "inline-block",
    fontWeight: font.regular,
    fontFeatureSettings: '"liga" 1, "dlig" 1',
  },
  role: {
    fontFamily: font.display,
    fontSize: { default: "19px", [media.deskPhone]: "18px" },
    marginTop: space.md,
    marginBottom: space.md,
  },
  body: {
    fontFamily: font.mono,
    fontSize: { default: "13px", [media.deskPhone]: "13px" },
    lineHeight: 1.95,
    color: color.muted,
    maxWidth: "400px",
    marginInline: "auto",
  },
});
