import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  shadow,
  shape,
  space,
  lighting,
  material,
} from "#design/tokens.stylex";

const wave = stylex.keyframes({
  "0%, 35%, 100%": { transform: "rotate(0deg)" },
  "7%, 21%": { transform: "rotate(18deg)" },
  "14%, 28%": { transform: "rotate(-10deg)" },
});
export const desk = stylex.create({
  scene: {
    position: "relative",
    maxWidth: "1600px",
    marginInline: "auto",
    width: "100%",
    height: {
      default: `max(800px, calc(100svh - ${shape.header}))`,
      [media.compact]: "auto",
    },
    paddingInline: {
      default: 0,
      [media.compact]: "28px",
      [media.phone]: "24px",
    },
    paddingBottom: { default: 0, [media.compact]: "48px" },
  },
  objects: {
    display: { default: "contents", [media.compact]: "block" },
    position: "relative",
    height: {
      default: "auto",
      [media.tablet]: "clamp(1000px, calc(1680px - 88vw), 1152px)",
      [media.phone]: "1790px",
    },
    maxWidth: {
      default: "none",
      [media.tablet]: "820px",
      [media.phone]: "440px",
    },
    marginInline: "auto",
  },
  glow: {
    position: "absolute",
    width: { default: "1150px", [media.compact]: "140%" },
    height: "min(820px, 100%)",
    top: "0px",
    left: "50%",
    transform: "translateX(-50%)",
    backgroundImage: `radial-gradient(ellipse, ${material.glow} 0%, ${lighting.warmth} 40%, transparent 70%)`,
    opacity: lighting.glowOpacity,
    transition: `opacity ${motionToken.slow} ease`,
    pointerEvents: "none",
  },
  intro: {
    position: { default: "absolute", [media.compact]: "relative" },
    top: { default: "48%", [media.compact]: "auto" },
    left: { default: "50%", [media.compact]: "auto" },
    transform: { default: "translate(-50%, -50%)", [media.compact]: "none" },
    width: { default: "42%", [media.compact]: "100%" },
    maxWidth: "560px",
    marginInline: "auto",
    textAlign: "center",
    zIndex: motionToken.objects,
    gridColumnStart: "1",
    gridColumnEnd: "-1",
    paddingTop: { default: "0", [media.compact]: "165px" },
    paddingBottom: { default: "0", [media.compact]: "72px" },
  },
  eyebrow: {
    fontFamily: font.mono,
    fontSize: font.large,
    letterSpacing: "0.05em",
    color: color.muted,
    marginBottom: space.md,
  },
  wave: {
    display: "inline-block",
    fontSize: "28px",
    marginRight: space.xs,
    transformOrigin: "70% 75%",
    animationName: { default: wave, [media.reduce]: "none" },
    animationDuration: motionToken.wave,
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  title: {
    fontFamily: font.handwritten,
    fontSize: {
      default: "clamp(60px, 6vw, 90px)",
      [media.tablet]: "80px",
      [media.phone]: "clamp(46px, 13vw, 72px)",
    },
    letterSpacing: "-0.035em",
    fontWeight: font.regular,
    lineHeight: 1.25,
    outline: "none",
  },
  name: {
    display: "inline-block",
    fontWeight: font.regular,
    fontFeatureSettings: '"liga" 1, "dlig" 1',
  },
  role: {
    fontFamily: font.display,
    fontSize: { default: "19px", [media.phone]: "18px" },
    marginTop: space.md,
    marginBottom: space.md,
  },
  body: {
    fontFamily: font.mono,
    fontSize: { default: "13px", [media.phone]: "13px" },
    lineHeight: 1.95,
    color: color.muted,
    maxWidth: "400px",
    marginInline: "auto",
  },
  slot: {
    maxWidth: "100%",
    position: "absolute",
    zIndex: {
      default: motionToken.objects,
      ":hover": motionToken.tooltip,
      ":has(:focus-visible)": motionToken.tooltip,
    },
  },
  computer: {
    top: { default: "8%", [media.compact]: "20px" },
    left: { default: "1.5%", [media.compact]: "0" },
    width: {
      default: "clamp(270px, 22vw, 300px)",
      [media.tablet]: "300px",
      [media.phone]: "300px",
    },
  },
  books: {
    bottom: { default: "5%", [media.compact]: "auto" },
    top: { default: "auto", [media.tablet]: "420px", [media.phone]: "785px" },
    left: { default: "7%", [media.tablet]: "4%", [media.phone]: "12px" },
  },
  record: {
    top: {
      default: "20px",
      [media.tablet]: "clamp(95px, calc(1310px - 135vw), 430px)",
      [media.phone]: "485px",
    },
    right: { default: "3%", [media.tablet]: "0", [media.phone]: "-5px" },
  },
  letter: {
    bottom: { default: "8%", [media.compact]: "auto" },
    top: {
      default: "auto",
      [media.tablet]: "clamp(500px, calc(1270px - 90vw), 730px)",
      [media.phone]: "1510px",
    },
    right: { default: "6%", [media.tablet]: "3%", [media.phone]: "5px" },
  },
  calendar: {
    bottom: { default: "4%", [media.compact]: "auto" },
    top: {
      default: "auto",
      [media.tablet]: "730px",
      [media.phone]: "1100px",
    },
    left: { default: "32%", [media.tablet]: "10%", [media.phone]: "auto" },
    right: { default: "auto", [media.phone]: "0" },
  },
  coffee: {
    bottom: { default: "6%", [media.compact]: "auto" },
    top: {
      default: "auto",
      [media.tablet]: "clamp(800px, calc(1483px - 89vw), 948px)",
      [media.phone]: "1310px",
    },
    right: { default: "33%", [media.tablet]: "36%", [media.phone]: "auto" },
    left: { default: "auto", [media.phone]: "-5px" },
    pointerEvents: "none",
  },
  pencil: {
    position: "absolute",
    width: "7px",
    height: "100px",
    backgroundImage: material.pencil,
    borderRadius: "2px",
    left: { default: "30%", [media.tablet]: "50%", [media.phone]: "78%" },
    top: {
      default: "0",
      [media.tablet]: "auto",
      [media.phone]: "1325px",
    },
    bottom: { default: "auto", [media.tablet]: "-20px", [media.phone]: "auto" },
    transform: { default: "rotate(75deg)", [media.phone]: "rotate(30deg)" },
    boxShadow: shadow.detail,
    pointerEvents: "none",
  },
  pencilTip: {
    position: "absolute",
    bottom: "-17px",
    width: "7px",
    height: "20px",
    backgroundImage: material.pencilTip,
    clipPath: "polygon(0 0,100% 0,50% 100%)",
  },
});
