import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  space,
  lighting,
  lampIntensity,
  material,
} from "#design/tokens.stylex";

const wave = stylex.keyframes({
  "0%, 35%, 100%": { transform: "rotate(0deg)" },
  "7%, 21%": { transform: "rotate(18deg)" },
  "14%, 28%": { transform: "rotate(-10deg)" },
});
export const desk = stylex.create({
  scene: {
    position: "relative",
    width: "100%",
    maxWidth: "1440px",
    marginInline: "auto",
    containerType: "inline-size",
    containerName: "desk",
    height: { default: "auto", [media.deskWide]: "100%" },
  },
  grid: {
    position: "relative",
    height: { default: "100%", [media.deskCompact]: "auto" },
    display: { default: "block", [media.deskCompact]: "grid" },
    gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
    columnGap: 0,
    rowGap: { default: "48px", [media.deskPhone]: "40px" },
    paddingInline: { default: 0, [media.deskCompact]: "24px" },
    paddingBottom: { default: 0, [media.deskCompact]: "64px" },
    alignItems: "center",
  },
  glow: {
    position: "absolute",
    width: "min(1150px, 100%)",
    height: {
      default: "100%",
      [media.deskCompact]: "900px",
      [media.deskPhone]: "760px",
    },
    top: { default: "-6%", [media.deskCompact]: "0px" },
    left: "50%",
    transform: "translateX(-50%)",
    backgroundImage: `radial-gradient(ellipse, ${material.glow} 0%, ${lighting.warmth} 40%, transparent 70%)`,
    opacity: lampIntensity.glowOpacity,
    transitionProperty: "opacity",
    transitionDuration: { default: motionToken.slow, [media.reduce]: "0s" },
    transitionTimingFunction: "ease",
    pointerEvents: "none",
  },
  intro: {
    width: "100%",
    textAlign: "center",
    overflowWrap: "anywhere",
  },
  eyebrow: {
    fontFamily: font.mono,
    fontSize: { default: "18px", [media.deskCompact]: font.large },
    letterSpacing: "0.05em",
    color: color.muted,
    marginBottom: { default: "10px", [media.deskCompact]: space.md },
  },
  wave: {
    display: "inline-block",
    fontSize: { default: "23px", [media.deskCompact]: "28px" },
    marginRight: space.xs,
    transformOrigin: "70% 75%",
    animationName: { default: wave, [media.reduce]: "none" },
    animationDuration: motionToken.wave,
    animationIterationCount: "infinite",
    animationTimingFunction: "ease-in-out",
  },
  title: {
    fontFamily: font.handwritten,
    fontSize: {
      default: "clamp(58px, 5cqw, 72px)",
      [media.deskShort]: "58px",
      [media.deskTablet]: "72px",
      [media.deskPhone]: "clamp(46px, 13cqw, 72px)",
    },
    letterSpacing: "-0.035em",
    fontWeight: font.regular,
    lineHeight: 1.25,
    outline: "none",
  },
  name: {
    display: "inline-block",
    maxWidth: "100%",
    fontWeight: font.regular,
    fontFeatureSettings: '"liga" 1, "dlig" 1',
  },
  role: {
    fontFamily: font.display,
    fontSize: { default: "17px", [media.deskCompact]: "18px" },
    marginTop: { default: "10px", [media.deskCompact]: space.md },
    marginBottom: { default: "12px", [media.deskCompact]: space.md },
  },
  body: {
    fontFamily: font.mono,
    fontSize: { default: "13px", [media.deskPhone]: "13px" },
    lineHeight: { default: 1.8, [media.deskCompact]: 1.95 },
    color: color.muted,
    maxWidth: "400px",
    marginInline: "auto",
  },
});
