import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  media,
  motionToken,
  shape,
  space,
  material,
} from "#design/tokens.stylex";

import { objectMarker } from "../../_design/object-feedback.stylex";
export const shell = stylex.create({
  headerActions: { display: "flex", alignItems: "center", gap: space.md },
  root: {
    "::selection": { backgroundColor: color.selection, color: color.text },
    backgroundColor: color.canvas,
    color: color.text,
    fontFamily: font.body,
    minHeight: "100svh",
    overflowX: "clip",
    display: "flex",
    flexDirection: "column",
    backgroundImage: `radial-gradient(${color.texture} 0.6px, transparent 0.6px)`,
    backgroundSize: "5px 5px",
  },
  progress: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    height: shape.progress,
    backgroundColor: color.accent,
    transformOrigin: "0% 50%",
    pointerEvents: "none",
    zIndex: 90,
  },
  header: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBlock: space.md,
    paddingInline: { default: space.xl, [media.phone]: space.md },
    gap: space.lg,
    flexWrap: "nowrap",
    height: shape.header,
    position: "sticky",
    top: 0,
    flexShrink: 0,
    isolation: "isolate",
    "::before": {
      content: '""',
      position: "absolute",
      inset: "0 0 -16px",
      backgroundColor: color.navigationGlass,
      backdropFilter: "blur(10px)",
      opacity: 0,
      zIndex: -1,
      pointerEvents: "none",
      maskImage: material.menuMask,
      transitionProperty: "opacity, bottom",
      transitionDelay: { default: "80ms", [media.reduce]: "0s" },
      transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
      transitionTimingFunction: motionToken.ease,
    },
    zIndex: 20,
  },
  headerScrolled: { "::before": { opacity: 1 } },
  headerMenu: {
    "::before": {
      bottom: { default: "-16px", [media.phone]: "-190px" },
      transitionDelay: "0s",
    },
  },
  nav: {
    display: "flex",
    gap: { default: space.xl, [media.phone]: space.lg },
    width: "auto",
    justifyContent: { default: "flex-start", [media.phone]: "space-between" },
  },
  link: {
    position: "relative",
    fontFamily: font.mono,
    fontSize: { default: font.navigation, [media.phone]: font.bodySize },
    display: "inline-flex",
    alignItems: "center",
    minHeight: shape.touch,
    color: {
      default: color.text,
      ":hover": color.accent,
      ":focus-visible": color.accent,
    },
    transition: `color ${motionToken.normal} ease`,
  },
  current: { color: color.accent },
  dot: {
    position: "absolute",
    bottom: 0,
    left: "calc(50% - 2.5px)",
    width: "5px",
    height: "5px",
    borderRadius: shape.round,
    backgroundColor: "currentColor",
    opacity: {
      default: 0,
      [stylex.when.ancestor(":hover", objectMarker)]: 1,
      [stylex.when.ancestor(":focus-visible", objectMarker)]: 1,
    },
    transition: `opacity ${motionToken.normal} ease`,
  },
  currentDot: { opacity: 1 },
  content: { display: "flex", flexDirection: "column", minHeight: "100svh" },
  homeContent: {
    height: { default: "100svh", [media.compact]: "auto" },
    overflowY: { default: "clip", [media.compact]: "visible" },
  },
  main: { flexGrow: 1, minHeight: 0 },
  skip: {
    position: "fixed",
    left: space.md,
    top: space.md,
    zIndex: 110,
    padding: space.md,
    backgroundColor: color.surface,
    transform: { default: "translateY(-200%)", ":focus": "translateY(0)" },
  },
  curtain: {
    position: "fixed",
    inset: 0,
    backgroundColor: color.curtain,
    color: color.curtainText,
    zIndex: motionToken.overlay,
    display: "flex",
    flexDirection: "column",
    gap: space.lg,
    outline: "none",
    alignItems: "center",
    justifyContent: "center",
    willChange: "transform",
  },
  curtainLoading: {
    minHeight: 0,
    flexGrow: "0",
    flexShrink: "0",
    flexBasis: "auto",
  },
  curtainActions: { textAlign: "center", fontSize: font.control },
  curtainButtons: {
    display: "flex",
    justifyContent: "center",
    gap: space.md,
    marginTop: space.sm,
  },
  curtainButton: {
    minHeight: shape.touch,
    paddingInline: space.md,
    borderWidth: shape.fine,
    borderStyle: "solid",
    borderColor: color.curtainText,
    borderRadius: shape.control,
    color: color.curtainText,
    backgroundColor: "transparent",
    cursor: "pointer",
    fontFamily: font.body,
  },
  curveTop: {
    position: "absolute",
    top: "-12vh",
    height: "14vh",
    width: "100%",
    backgroundColor: color.curtain,
    borderTopLeftRadius: "50%",
    borderTopRightRadius: "50%",
    borderBottomRightRadius: 0,
    borderBottomLeftRadius: 0,
  },
  curveBottom: {
    position: "absolute",
    bottom: "-12vh",
    height: "14vh",
    width: "100%",
    backgroundColor: color.curtain,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomRightRadius: "50%",
    borderBottomLeftRadius: "50%",
  },
  word: {
    fontSize: "clamp(36px, 5vw, 62px)",
    fontWeight: font.regular,
    display: "flex",
    gap: space.lg,
    alignItems: "center",
  },
  wordDot: {
    width: "9px",
    height: "9px",
    borderRadius: shape.round,
    backgroundColor: color.curtainText,
  },
  hidden: { visibility: "hidden", pointerEvents: "none" },
});
