import * as stylex from "@stylexjs/stylex";

import {
  color,
  font,
  layer,
  media,
  motionToken,
  space,
  shape,
} from "#design/tokens.stylex";

const top = "clamp(132px, 18dvh, 180px)";
const expandedWidth = "min(304px, calc(100vw - 48px))";
const desktopLeft = `calc(50% + ${shape.reading} / 2 + ${space.md})`;
const desktopWidth = `min(232px, calc(50vw - ${shape.reading} / 2 - ${space.md} - ${space.lg}))`;
const availableHeight = `calc(100dvh - ${top} - 24px)`;

export const tocStyles = stylex.create({
  root: {
    position: "fixed",
    top,
    right: { default: "8px", [media.tocWide]: "auto" },
    left: { default: "auto", [media.tocWide]: desktopLeft },
    width: { default: "32px", [media.tocWide]: desktopWidth },
    maxHeight: availableHeight,
    paddingInline: { default: 0, [media.tocWide]: space.sm },
    isolation: "isolate",
    zIndex: 15,
    contain: "layout style",
    "--toc-motion-duration": motionToken.tocExpand,
    "--toc-motion-easing": motionToken.ease,
  },
  surface: {
    position: "absolute",
    inset: "-16px -8px -16px -24px",
    backgroundImage: color.tocVeil,
    opacity: 0,
    pointerEvents: "none",
    transformOrigin: "0 0",
    zIndex: -1,
  },
  surfaceExpanded: { opacity: 1, insetBlock: 0 },
  height: (count: number) => ({
    "--toc-compact-row-height": `min(18px, calc(${availableHeight} / ${count}))`,
    height: {
      default: `min(${count * 18}px, ${availableHeight})`,
      [media.tocWide]: "auto",
    },
  }),
  expanded: {
    top: 0,
    height: "100dvh",
    maxHeight: "100dvh",
    paddingBlock: 0,
    zIndex: layer.navigation,
    width: expandedWidth,
    paddingInline: space.md,
  },
  trigger: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    padding: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    cursor: "pointer",
    zIndex: 2,
    display: { default: "block", [media.tocWide]: "none" },
  },
  triggerHidden: { pointerEvents: "none", opacity: 0 },
  header: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    height: { default: 0, [media.tocWide]: "36px" },
    overflow: "hidden",
    whiteSpace: "nowrap",
    opacity: { default: 0, [media.tocWide]: 1 },
    transform: { default: "translateX(12px)", [media.tocWide]: "none" },
    color: color.text,
    fontSize: font.control,
    fontWeight: font.semibold,
    transitionProperty: "opacity, transform",
    transitionDuration: {
      default: motionToken.tocExpand,
      [media.reduce]: "0s",
    },
    transitionTimingFunction: motionToken.ease,
  },
  headerExpanded: { height: "36px", opacity: 1, transform: "none" },
  navigation: {
    maxHeight: {
      default: availableHeight,
      [media.tocWide]: `calc(${availableHeight} - 36px)`,
    },
    overflowY: { default: "clip", [media.tocWide]: "auto" },
    overflowX: { default: "clip", [media.tocWide]: "hidden" },
    overscrollBehavior: "contain",
    overflowAnchor: "none",
    scrollbarWidth: "none",
    "::-webkit-scrollbar": { display: "none" },
  },
  navigationExpanded: {
    height: "calc(100dvh - 36px)",
    maxHeight: "calc(100dvh - 36px)",
    overflowY: "auto",
    overflowX: "hidden",
  },
  list: { listStyleType: "none", margin: 0, padding: 0 },
  row: {
    position: "relative",
    height: {
      default: "var(--toc-compact-row-height)",
      [media.tocWide]: "30px",
    },
  },
  rowExpanded: {
    height: { default: "32px", [media.phone]: "40px" },
  },
  link: {
    display: "flex",
    alignItems: "center",
    position: "relative",
    height: "100%",
    width: "100%",
    color: { default: color.muted, ":hover": color.accentText },
    fontSize: font.control,
    lineHeight: 1.5,
    textDecoration: "none",
  },
  indicator: (strength: number) => ({
    position: "absolute",
    left: 0,
    top: 0,
    width: "1px",
    height: {
      default: "min(2px, calc(var(--toc-compact-row-height) / 3))",
      [media.tocWide]: "1px",
    },
    transformOrigin: "0 0",
    transform: {
      default: `translate(${16 - (10 + 18 * strength) / 2}px, calc((var(--toc-compact-row-height) - min(2px, calc(var(--toc-compact-row-height) / 3))) / 2)) scaleX(${10 + 18 * strength})`,
      [media.tocWide]: "scaleY(30)",
    },
    opacity: { default: 0.24 + 0.76 * strength, [media.tocWide]: 1 },
    backgroundColor: { default: color.text, [media.tocWide]: color.line },
    transitionProperty: "transform, opacity",
    transitionDuration: {
      default: motionToken.tocExpand,
      [media.reduce]: "0s",
    },
    transitionTimingFunction: motionToken.ease,
    pointerEvents: "none",
  }),
  indicatorExpanded: {
    height: "1px",
    transform: { default: "scaleY(32)", [media.phone]: "scaleY(40)" },
    opacity: 1,
    backgroundColor: color.line,
  },
  indicatorCurrent: {
    backgroundColor: { default: color.text, [media.tocWide]: color.accent },
  },
  indicatorCurrentExpanded: { backgroundColor: color.accent },
  text: (depth: number) => ({
    paddingLeft: `${12 + depth * 12}px`,
    paddingRight: space.xs,
    display: "block",
    maxHeight: "100%",
    width: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    opacity: { default: 0, [media.tocWide]: 1 },
    transform: { default: "translateX(16px)", [media.tocWide]: "none" },
    transitionProperty: "opacity, transform",
    transitionDuration: { default: motionToken.normal, [media.reduce]: "0s" },
    transitionTimingFunction: motionToken.ease,
    pointerEvents: "none",
  }),
  textExpanded: (order: number) => ({
    opacity: 1,
    transform: "none",
    transitionDelay: {
      default: `${60 + Math.min(order, 10) * 12}ms`,
      [media.reduce]: "0s",
    },
  }),
  current: { color: color.accentText, fontWeight: font.medium },
});
