import * as stylex from "@stylexjs/stylex";

import { font, shape, space, material } from "#design/tokens.stylex";

export const panel = stylex.create({
  statLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    color: "inherit",
  },
  title: {
    fontSize: font.small,
    fontWeight: font.medium,
    letterSpacing: "0.05em",
    marginBottom: space.sm,
  },
  muted: { opacity: 0.7, fontSize: font.tiny, lineHeight: 1.5 },
  rows: { display: "grid", gap: space.xs },
  row: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    fontSize: font.small,
    paddingBlock: "2px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: material.highlight,
  },
  value: {
    fontSize: font.large,
    fontVariantNumeric: "tabular-nums",
    fontWeight: font.medium,
  },
  actions: {
    display: "flex",
    gap: space.sm,
    marginTop: space.xs,
    flexWrap: "wrap",
  },
  button: {
    minHeight: shape.touch,
    paddingInline: space.xxs,
    paddingBlock: 0,
    borderWidth: 0,
    borderRadius: shape.small,
    backgroundColor: "transparent",
    color: material.phosphor,
    fontFamily: font.mono,
    fontSize: font.small,
    opacity: { default: 0.75, ":hover": 1, ":focus-visible": 1 },
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  chosen: {
    opacity: 1,
    textDecorationLine: "underline",
    textUnderlineOffset: "5px",
  },
  guestbook: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  page: { minHeight: 0, flexGrow: 1, overflow: "hidden" },
  read: {
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarWidth: "none",
    userSelect: "none",
  },
  list: {
    margin: 0,
    padding: 0,
    listStyleType: "none",
    display: "grid",
    gap: space.sm,
  },
  entry: {
    paddingBottom: space.sm,
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: material.highlight,
    fontSize: font.small,
    overflowWrap: "anywhere",
  },
  byline: {
    display: "flex",
    alignItems: "flex-start",
    gap: space.xs,
    marginBottom: space.xxs,
  },
  author: {
    minWidth: 0,
    flexGrow: 1,
    display: "flex",
    flexDirection: "column",
  },
  authorName: { fontSize: font.small, lineHeight: 1.5 },
  date: { flexShrink: 0, fontSize: font.tiny, opacity: 0.7, lineHeight: 1.8 },
  email: { fontSize: font.tiny, opacity: 0.65, overflowWrap: "anywhere" },
  message: { whiteSpace: "pre-wrap", lineHeight: 1.6 },
  metric: {
    display: "inline-flex",
    alignItems: "center",
    gap: space.xs,
    minHeight: shape.touch,
    fontSize: font.small,
    opacity: 0.75,
    fontVariantNumeric: "tabular-nums",
  },
  form: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: space.xxs,
  },
  identity: {
    display: "grid",
    gridTemplateColumns: "18px minmax(0, 1fr)",
    alignItems: "center",
    gap: space.xs,
    minHeight: "36px",
    fontSize: font.small,
  },
  fieldIcon: {
    width: "18px",
    height: "18px",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.5,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    opacity: 0.7,
  },
  messageIcon: { marginTop: space.xxs },
  messageField: {
    alignItems: "start",
    gridTemplateRows: "minmax(0, 1fr)",
    flexGrow: 1,
    minHeight: 0,
  },
  field: {
    minWidth: 0,
    width: "100%",
    minHeight: "32px",
    borderWidth: 0,
    borderRadius: 0,
    paddingBlock: space.xxs,
    paddingInline: 0,
    backgroundColor: "transparent",
    color: material.phosphor,
    fontFamily: font.mono,
    fontSize: font.small,
    lineHeight: 1.6,
    caretColor: material.phosphor,
    // oxlint-disable-next-line @stylexjs/valid-styles -- Progressive CSS caret-shape is not yet in StyleX's property list.
    caretShape: "block",
    "::placeholder": { color: material.phosphor, opacity: 0.5 },
    outlineStyle: "none",
    textShadow: { ":focus": `0 0 8px ${material.highlight}` },
  },
  textarea: { height: "100%", minHeight: 0, resize: "none", overflowY: "auto" },
  submitRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: space.xs,
  },
  notice: {
    display: "block",
    fontSize: font.tiny,
    lineHeight: 1.5,
    marginTop: space.xxs,
    flexShrink: 0,
  },
});
