import * as stylex from "@stylexjs/stylex";

import { color, font, shape, space, shadow } from "#design/tokens.stylex";

export const codeStyles = stylex.create({
  root: {
    width: "100%",
    minWidth: 0,
    position: "relative",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.control,
    overflow: "hidden",
    backgroundColor: color.surfaceMuted,
    color: color.codeText,
  },
  toolbar: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: space.xs,
    paddingBlock: space.xs,
    paddingInline: space.sm,
    fontFamily: font.mono,
    fontSize: font.small,
  },
  language: {
    marginRight: "auto",
    minWidth: 0,
    maxWidth: "65%",
    color: color.muted,
    backgroundColor: "transparent",
    borderWidth: 0,
  },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    minHeight: "30px",
    borderWidth: 0,
    borderRadius: shape.small,
    padding: space.xs,
    backgroundColor: { default: "transparent", ":hover": color.surfaceHover },
    color: { default: color.muted, ":hover": color.text },
    cursor: "pointer",
    fontSize: font.small,
  },
  languageInput: {
    width: "168px",
    fontFamily: font.mono,
    fontSize: font.small,
    height: "30px",
    paddingInline: "6px",
    borderRadius: shape.small,
    outline: { default: "none", ":focus-visible": `2px solid ${color.focus}` },
    backgroundColor: {
      default: "transparent",
      ":hover": color.surfaceHover,
      ":focus": color.surface,
    },
  },
  suggestions: {
    position: "fixed",
    margin: 0,
    padding: "4px",
    width: "240px",
    maxWidth: "calc(100vw - 24px)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.control,
    backgroundColor: color.surface,
    color: color.text,
    boxShadow: shadow.panel,
    overflowY: "auto",
    overscrollBehavior: "contain",
    fontFamily: font.body,
    fontSize: font.small,
  },
  option: {
    paddingBlock: "8px",
    paddingInline: "10px",
    borderRadius: shape.small,
    cursor: "pointer",
    backgroundColor: { default: "transparent", ":hover": color.surfaceHover },
  },
  optionSelected: {
    backgroundColor: color.accentSurface,
    color: color.accentText,
  },
  empty: { padding: "12px", color: color.muted },
  diagram: {
    display: "block",
    width: "100%",
    padding: space.sm,
    backgroundColor: color.surface,
    borderWidth: 0,
  },
  image: {
    display: "block",
    maxWidth: "100%",
    height: "auto",
    marginInline: "auto",
  },
  notice: { color: color.muted, padding: space.sm, fontSize: font.small },
});
