import * as stylex from "@stylexjs/stylex";

import { color, font, shape, space, motionToken } from "#design/tokens.stylex";
export const cardStyles = stylex.create({
  card: {
    display: "flex",
    flexDirection: {
      default: "row",
      "@container media-column (min-width: 0px)": "column-reverse",
    },
    width: "100%",
    minWidth: 0,
    minHeight: "128px",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.control,
    backgroundColor: {
      default: color.surface,
      ":hover": color.surfaceMuted,
      ":focus-visible": color.surfaceMuted,
    },
    color: color.text,
    textDecoration: "none",
    transitionProperty: "background-color",
    transitionDuration: {
      default: motionToken.fast,
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    outlineOffset: "3px",
  },
  copy: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "5px",
    padding: space.md,
    minWidth: 0,
    flex: "1",
  },
  title: {
    fontSize: font.bodySize,
    fontWeight: font.semibold,
    lineHeight: 1.4,
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
    overflow: "hidden",
  },
  description: {
    fontSize: font.small,
    lineHeight: 1.5,
    color: color.muted,
    display: "-webkit-box",
    WebkitBoxOrient: "vertical",
    WebkitLineClamp: 2,
    overflow: "hidden",
    overflowWrap: "anywhere",
  },
  source: {
    fontSize: font.small,
    lineHeight: 1.4,
    color: color.muted,
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    minWidth: 0,
  },
  site: { overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis" },
  domain: {
    fontSize: font.tiny,
    color: color.muted,
    lineHeight: 1.4,
    overflow: "hidden",
    whiteSpace: "nowrap",
    textOverflow: "ellipsis",
  },
  image: {
    width: {
      default: "144px",
      "@container media-column (min-width: 0px)": "100%",
    },
    height: {
      default: null,
      "@container media-column (min-width: 0px)": "140px",
    },
    flexShrink: 0,
    objectFit: "cover",
    alignSelf: "stretch",
    maxHeight: "160px",
    maxWidth: {
      default: "30%",
      "@container media-column (min-width: 0px)": "100%",
    },
  },
  logo: { width: "16px", height: "16px", objectFit: "contain", flexShrink: 0 },
  tools: {
    display: "flex",
    gap: space.xs,
    paddingBlock: space.xs,
    alignItems: "center",
  },
  editor: { width: "100%", minWidth: 0 },
  urlBar: {
    display: "flex",
    alignItems: "center",
    gap: space.xs,
    paddingBlock: space.xs,
    color: color.muted,
  },
  urlInput: {
    minWidth: 0,
    flex: "1",
    borderWidth: 0,
    backgroundColor: "transparent",
    color: color.text,
    padding: space.xxs,
    fontFamily: font.body,
    fontSize: font.small,
    outlineOffset: "2px",
  },
  iconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "28px",
    height: "28px",
    borderWidth: 0,
    borderRadius: shape.small,
    backgroundColor: { default: "transparent", ":hover": color.surfaceMuted },
    color: color.muted,
    cursor: "pointer",
    opacity: { default: 1, ":disabled": 0.4 },
  },
  notice: {
    display: "block",
    fontSize: font.small,
    color: color.muted,
    lineHeight: 1.5,
  },
  button: {
    fontSize: font.small,
    padding: space.xs,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: color.line,
    borderRadius: shape.small,
    backgroundColor: color.surface,
    color: color.text,
    cursor: "pointer",
  },
});
